--- #YAML:1.0
name:                Parse-Flex
version:             0.12
abstract:            The Fastest Lexer in the West 
license:             gpl
author:              
    - Ioannis Tambouras <ioannis@earthlink.net>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Scalar::Util:                  0
    XSLoader:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
