# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Parse-Flex
version:      0.11
version_from: lib/Parse/Flex.pm
installdirs:  site
requires:
    Scalar::Util:                  0
    XSLoader:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
