--- #YAML:1.0
name: Parse-Flex
version: 0.10
author:
  - Ioannis Tambouras <ioannis@yahoo.com>
abstract: The Fastest Lexer in the West
license: perl
requires:
  Scalar::Util: 0
  XSLoader: 0
  perl: 5.6
recommends:
  Pod::Checker: 0
  Test::Distribution: 1.22
  Test::Exception: 0
  Test::Pod: 1.20
  Test::Pod::Coverage: 1.06
provides:
  Parse::Flex:
    file: lib/Parse/Flex.pm
    version: 0.10
  Parse::Flex::Generate:
    file: lib/Parse/Flex/Generate.pm
    version: 0.01
generated_by: Module::Build version 0.2611
